### ISSUE TITLE
ClearTech Invoice

### ISSUE THREAD

**Issue by esarks** [esarks/Royal-Palms-Accounting#17]
https://github.com/esarks/Royal-Palms-Accounting/blob/master/Invoices/2018-08/Royal%20Palm%20Villages%20Invoicing.pdf

**Comment by esarks** [comment]
Add email response to ClearTech requesting payment/invoice matching information.

https://github.com/esarks/Royal-Palms-Accounting/blob/master/Invoices/2018-08/The%20Marshalls%20Mail%20-%20Re_%20Clear-Tech%2C%20Inc_%2314618.pdf

Scheduled payment for 1 of 3 invoices pending reconciliation report from Clear-Tech:

https://github.com/esarks/Royal-Palms-Accounting/blob/master/Invoices/2018-08/Clear-Tech%20Payments%20-%20Pay%20your%20bills%20-%20Regions%20Online%20Banking.pdf

**Comment by esarks** [comment]
Moved card to Bill Pay Submitted.

**Comment by esarks** [comment]
Received statement of reconciliation from Clear-Tech.

TODO:  Set up past due payments.

https://github.com/esarks/Royal-Palms-Accounting/blob/master/Invoices/2018-08/Statement%20for%20customer%200014618.PDF

**Comment by martypetty** [comment]
Paul, I pulled this off the bank ledger. I called them at one point in the
time period because we were missing invoices.  They said they had had some
issues - so in our transition, I dropped the ball on this. The dollars are
of course budgeted.
Thanks and sorry for your need to clean up.


*Marty*

2018 IS THE YEAR OF THE ROCKSTARIT'S TIME TO FOCUS ON YOUR PEOPLE!

Marty Petty
President & CEO



727.580.7317
*marty@mpettygroup.com <marty@mpettygroup.com>*
http://www.mpettygroup.com/

7235 First Ave. S., Suite A
Gulfport, FL  33707

The information contained in this e-mail is confidential and may be
privileged.  If you are not the intended recipient, then (i) any
dissemination, distribution or reproduction of this email is strictly
prohibited; and (ii) please notify us by email of the error in transmission
and delete it from your computer immediately.

Thank you.

**Comment by esarks** [comment]
I scheduled all payments to bring us current and communicated with Clear-Tech Mary Jo Lesperance.

**Comment by esarks** [comment]
Closed
